### ISSUE TITLE
T and right click is not turning on the bot.

### ISSUE THREAD

**Issue by SlitherHeatwaVe** [ermiyaeskandary/Slither.io-bot#207] opened 2016-05-23 07:50 UTC
Hello. I found that whenever I pressed right click or 'T', the bot wouldn't activate.

Is there a known solution to this issue. If so, could you be so kind to let me know how to fix this in the chat.
Thanks

I use windows 10, just in case that makes a difference ;)
Also, i have turned off every other mod and it made no difference, just so you know

**Comment by fudoido** [comment] 2016-05-23 10:38
same issue with me today, yesterday was fine, but today it goes in a straight line, not turning to avoid other sliths or colect points.

**Comment by Seple** [comment] 2016-05-23 11:52
bot not work

**Comment by ermiyaeskandary** [comment] 2016-05-23 12:23
From what commit ?

**Comment by tjorim** [comment] 2016-05-23 12:25
There hasn't been a commit since 3 days, perhaps the site script.

**Comment by ermiyaeskandary** [comment] 2016-05-23 12:25
Yeah - true...

**Comment by ermiyaeskandary** [comment] 2016-05-23 12:25
Can you confirm it @tjorim ?

**Comment by jestjosh** [comment] 2016-05-23 14:23
Found an issue working on a fix

**Comment by ermiyaeskandary** [comment] 2016-05-23 14:39
@code-bash Was going to check but great!

**Comment by fudoido** [comment] 2016-05-23 15:41
i been using chither.com bots  (the free ones to get more points hehe) along with yours, dont know if that might caused the error or not, and dont know if OP was using it also or not.
in any case, was working the last couple days when i started using chither bots, and today even without them, your bot keeps going allways ahead in one direction, not going for points nor avoiding other snakes.

**Comment by jestjosh** [comment] 2016-05-23 16:21
@ErmiyaEskandary I was getting collisionGrid not defined. I fixed that now get this. You may now more about this error unless my change to the grid caused it. 
  Error during WebSocket handshake: Unexpected response code: 302

**Comment by chaseoes** [comment] 2016-05-23 16:22
It's broken for me now as well. I can enable it but it just goes in a straight line until it dies.

**Comment by ermiyaeskandary** [comment] 2016-05-23 17:19
@code-bash Yeah - what I expected. Server code change...

**Comment by ermiyaeskandary** [comment] 2016-05-23 17:41
@codebash Please make a PR with your fix so then we can work on the fix for this issue.

**Comment by lukec11** [comment] 2016-05-23 18:12
Confirmed, it will enable sometimes but when it is enabled it will move in a straight line.

**Comment by clemens-tolboom** [comment] 2016-05-23 18:47
Should we report server versions?
- worked for (my?) server version May 21 16:12 game404ee.js
- broken for (my?) server version May 23 19:57 game515do.js

**Comment by ermiyaeskandary** [comment] 2016-05-23 20:11
Game code shouldn't change a lot - we just need to adjust the getters so they match with current game code.

**Comment by ermiyaeskandary** [comment] 2016-05-23 20:12
Visual debugging doesn't also work :( 100% related to client code

**Comment by bollidtzo** [comment] 2016-05-23 20:18
> WebSocket handshake: Unexpected response code: 302

Does a websocket convey a UserAgent?

**Comment by SlitherHeatwaVe** [comment] 2016-05-23 22:26
Also, I have this issue where I try to press 't', it doesn't turn it on. But when I press 't' while the bot is enabled, it disables it, even though it being enabled is completely useless. After that, the 't' button can't do anything.

Although, by pressing 'y' which is the visual debugging, after pressing 't'  I can make the bot _appear_ to be enabled again, even though it is not.

I just thought this might be noteworthy.
Thanks =)

**Comment by tjorim** [comment] 2016-05-23 23:11
The bot should be fixed now, check for updates in tamper-/greasemonkey or just install it again [here](https://github.com/ErmiyaEskandary/Slither.io-bot/raw/master/bot.meta.user.js).

PS: @SlitherHeatwaVe, could you please open a new issue for that? Thanks in advance! :+1:

**Comment by SlitherHeatwaVe** [comment] 2016-05-23 23:19
Oh, it is completely fine now. That was probably an issue related to the same as now cause that is completely fixed :+1: 

Also, nice bot, it's working amazingly. Keep up the good work ! :+1:

**Comment by fudoido** [comment] 2016-05-24 00:42
can confirm that is back on again. thanks mates :)

**Comment by hnphi** [comment] 2016-05-24 03:33
I see black screen, when i install lastest version. The bots not working with me.
And i see error like this: `Uncaught ReferenceError: collisionGrid is not defined`
Please help me!

**Comment by tjorim** [comment] 2016-05-24 05:18
@pomega You sure you installed the right file? Please remove the script and
install it again using the link above (or the one in the ReadMe).

**Comment by ermiyaeskandary** [comment] 2016-05-24 05:51
@pomega Someone in Gitter had a old version and got a black screen but then he updated his script and it was fixed. @tjorim 's comment above should help. I'll also say check that you don't have other scripts enabled...

**Closed as completed** 2016-05-24 05:52 UTC
Labels: type:bug, status:confirmed

**Comment by ermiyaeskandary** [comment] 2016-05-24 05:55
> The bot should be fixed now, check for updates in tamper-/greasemonkey or just install it again [here](https://raw.githubusercontent.com/ErmiyaEskandary/Slither.io-bot/master/bot.meta.user.js).
