### ISSUE TITLE
How to avoid collisions with other worms?

### ISSUE THREAD

**Issue by vectorserver** [ermiyaeskandary/Slither.io-bot#44] opened 2016-05-03 07:16 UTC
How to avoid collisions with other worms?

**Comment by ermiyaeskandary** [comment] 2016-05-03 12:28
Duplicate of #18 : 
https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Bug-reporting

> To report a bug start by: Searching for existing issue reports. No one wants to deal with duplicate reports.

**Closed as completed by ermiyaeskandary** 2016-05-03 12:28 UTC
