### ISSUE TITLE
Snake's eyes green sometimes

### ISSUE THREAD

**Issue by ermiyaeskandary** [ermiyaeskandary/Slither.io-bot#21] opened 2016-04-28 16:45 UTC

**Comment by tjbcg** [comment] 2016-04-28 16:48
Potentially fixed with last commit. Needs testing

**Comment by ghost** [comment] 2016-04-29 04:00
I still see green snake eyes

**Comment by tjbcg** [comment] 2016-04-30 16:06
We all do @TheFlyingPlatypus . Unfortunately, we don't know why this is caused (as for #17).

**Comment by ermiyaeskandary** [comment] 2016-05-01 14:03
Also happens for border. Hint ?

**Comment by tjbcg** [comment] 2016-05-01 14:52
I think it is caused by the property `strokeStyle` of canvas' context.  That's what I tried to do with b5f4c7c, but it looks like the change has to be applied (committed) on the context.

**Comment by tjbcg** [comment] 2016-05-01 14:52
That would explain why only the border of the snake's eyes are green

**Comment by ChadSki** [comment] 2016-05-13 06:48
Is this still an issue?

**Comment by ermiyaeskandary** [comment] 2016-05-13 07:07
Haven't seen it happening...

**Comment by Drflash55** [comment] 2016-05-13 11:48
So... I guess this has been fixed, and can be closed...?

**Closed as completed by Drflash55** 2016-05-13 11:48 UTC
Labels: type:bug, prio:low
