### ISSUE TITLE
Don't eat food behind snakes

### ISSUE THREAD

**Issue by ghost** [ermiyaeskandary/Slither.io-bot#103] opened 2016-05-08 17:56 UTC
it really is pointless trying to eat or especially boost for food that is in or behind a snake, and it usually gets your snake killed. so if the food is behind an enemy tail it should not be considered as food.

**Comment by Drflash55** [comment] 2016-05-08 17:56
Yeah, this is already made aware of, by me, several times...

I'm sure they are trying to fix this...

**Comment by ghost** [comment] 2016-05-08 17:57
where is duplicate?

**Comment by Drflash55** [comment] 2016-05-08 17:57
There is not an issue on here, but I said it on the gitter.im chat.

@ErmiyaEskandary Does that count?

**Comment by ghost** [comment] 2016-05-08 17:58
oh ok but at least there is an issue here

**Comment by ermiyaeskandary** [comment] 2016-05-08 18:12
@Drflash55 We need to make issues here . But thanks anyway. We are working on this surely...

**Comment by Seple** [comment] 2016-05-10 02:54
I reported the similar problem + photo #116

**Comment by Evanito** [comment] 2016-05-10 23:25
@Drflash55 Since Issues are our official means of workflow management, it is only a duplicate if there is another issue for the same topic.

**Comment by ChadSki** [comment] 2016-05-13 06:40
Fixed by [pull #143](https://github.com/ErmiyaEskandary/Slither.io-bot/pull/143)?

**Comment by Drflash55** [comment] 2016-05-13 11:47
Someone test out to see if [pull #143](https://github.com/ErmiyaEskandary/Slither.io-bot/pull/143) fixes the issue of the bot trying to go after food behind snakes...

**Comment by tjorim** [comment] 2016-05-13 12:23
No it seems as like it isn't fixed, checking if a path towards food is
clear has not been implemented yet.

**Comment by ermiyaeskandary** [comment] 2016-05-16 19:27
@OneEyed Done with the latest grid method implementation?

**Comment by ermiyaeskandary** [comment] 2016-05-17 15:10
Not evident for me - if confirmed **with the latest version** please reopen...

**Closed as completed by ermiyaeskandary** 2016-05-17 15:10 UTC
Labels: type:bug, status:confirmed
