### ISSUE TITLE
Settings keys do not work after dying

### ISSUE THREAD

**Issue by djoey123** [ermiyaeskandary/Slither.io-bot#126] opened 2016-05-10 15:56 UTC
When you die 1 time you cant press any settings key like: Y T U I etc. only when you are refresh the page

**Comment by tjorim** [comment] 2016-05-10 16:35
I can't seem to reproduce this, anyone else?

**Comment by ermiyaeskandary** [comment] 2016-05-10 16:39
Same here..

**Comment by djoey123** [comment] 2016-05-10 17:21
seems like it is a problem in Firefox i dont know in what browser you have test it? @ErmiyaEskandary @tjorim

**Comment by tjorim** [comment] 2016-05-10 18:58
Thanks for providing the additional information, are you using the latest version of firefox and the bot?
Do you use tampermonkey or greasemonkey?

**Comment by djoey123** [comment] 2016-05-10 19:08
i use the latest version of firefox and i use greasemonkey

**Comment by tjorim** [comment] 2016-05-10 19:11
Confirmed using bot v0.8.1, Firefox 46.0.1 and Tampermonkey beta as well.
Script still listens to mouseDown (toggle bot with right-click) but none of the keypresses are registered.

**Comment by tjorim** [comment] 2016-05-10 19:25
I narrowed it down to the

``` javascript
if (document.activeElement.parentElement !== window.nick_holder)
```

equation. It seems like pushing the play button doesn't...
Euhm, how do I say this in English? The inputfield doesn't lose focus?

**Comment by tjorim** [comment] 2016-05-10 20:34
@djoey123 I made an attempt to fix it, could you [click this link](https://github.com/tjorim/Slither.io-bot/raw/firefox-keyfix/bot.user.js) so it updates the script and try again?

**Comment by djoey123** [comment] 2016-05-11 14:59
Nope there is still a problem with it

**Comment by HamishBlank** [comment] 2016-05-11 21:27
I have had this problem also, however I have found that it has something to do with either the "Play" button or having the cursor in the nickname text box. If you click elsewhere on the page (like the background for example), then press enter you can use all keys (can also test if keys work before you press enter).

Hope this helps

**Comment by tjorim** [comment] 2016-05-12 04:00
Yes indeed @HamboBlank , that was my conclusion as well.
That's why it should be fixed. When reproducing this bug, it's now fixed on my pc with this new code.

When you click the playbutton, the current activeElement should lose its focus. Maybe a more specific approach like just letting the inputfield lose its focus or focussing on another item would be better.

**Comment by djoey123** [comment] 2016-05-12 18:44
Tested new version v0.8.3 now i cant press any key only the mouse keys. first time when i join i cant use any key. before it was only when the bot dies

**Comment by ermiyaeskandary** [comment] 2016-05-12 18:52
So we need to revert that code...

**Comment by ermiyaeskandary** [comment] 2016-05-12 18:55
We haven't changed anything - delete and install the latest script again. Nothing should have changed - we have only changed collision detection code :/

**Comment by tjorim** [comment] 2016-05-12 18:56
@djoey123 , like @HamboBlank said: for now you could try clicking outside the nickname-input before clicking the play-button. There weren't any changes that would make it worse.

**Comment by ermiyaeskandary** [comment] 2016-05-12 18:58
^

**Comment by tjorim** [comment] 2016-05-12 19:14
~~Could @djoey123 @HamboBlank or someone else who experiences the issue try again?
Just to be sure: follow the next steps...~~

~~1. Go into the scriptmanager
2. Remove the bot-userscript
3. https://github.com/tjorim/Slither.io-bot/raw/firefox-keyfix/bot.user.js <-- click and install this
4. Make sure NO OTHER SCRIPTS OR MODS are enabled
5. Restart your browser and open slither.io again~~

Edit: doesn't even work for me, don't even bother trying :unamused:

**Comment by tjorim** [comment] 2016-05-12 19:28
Could someone else test the earlier script I posted? Because that worked for me.
Use the same steps as I said in my previous post, it's just another install-link:
1. Go into the scriptmanager
2. Remove the bot-userscript
3. https://github.com/tjorim/Slither.io-bot/raw/7661b2633a20522234e587aaaef677f3fe0cad51/bot.user.js <-- click and install this
4. Make sure NO OTHER SCRIPTS OR MODS are enabled
5. Restart your browser and open slither.io again

**Comment by HamishBlank** [comment] 2016-05-12 20:22
@tjorim I have followed your instructions and it works for when you die, or press Q to quit. However when pressing ESC instead of the instant respawn I am taken to the menu like when pressing Q (not sure if intended or bug), the enter key or "play" button are not usable so a page refresh is required.

**Comment by tjorim** [comment] 2016-05-15 16:47
@HamboBlank Could you check one final time if it is resolved with the following script? https://github.com/tjorim/Slither.io-bot/raw/keyfix/bot.user.js

**Comment by djoey123** [comment] 2016-05-15 18:27
It is fixed for me @tjorim

**Comment by tjorim** [comment] 2016-05-15 18:36
Great! Making pull request now.

**Comment by ermiyaeskandary** [comment] 2016-05-15 18:38
:+1:

**Comment by HamishBlank** [comment] 2016-05-15 20:17
Sorry for the late reply, updated to new version and working now.

**Comment by ermiyaeskandary** [comment] 2016-05-15 20:48
Fixed..

**Closed as completed by ermiyaeskandary** 2016-05-15 20:48 UTC
Labels: type:bug, prio:normal, status:confirmed
