### ISSUE TITLE
[Bug] Latest commit broke bot

### ISSUE THREAD

**Issue by Salvationdk** [ermiyaeskandary/Slither.io-bot#186] opened 2016-05-17 07:50 UTC
Latest update broke bot..

**Comment by Salvationdk** [comment] 2016-05-17 08:07
downgraded to v. 0.93 and bot works again

**Comment by Drflash55** [comment] 2016-05-17 11:47
@ErmiyaEskandary @ChadSki Can you confirm that the latest version breaks the bot?

**Comment by xpassionzxc** [comment] 2016-05-17 12:09
i can confirm it does.

**Comment by ermiyaeskandary** [comment] 2016-05-17 12:20
Ah - ok.. Will look into it now...
From which commit ?

**Comment by ermiyaeskandary** [comment] 2016-05-17 12:20
Can you show me a console log ?

**Comment by Salvationdk** [comment] 2016-05-17 12:25
https://github.com/ErmiyaEskandary/Slither.io-bot/commit/fd169af7cd39769543581247065cd3f026d76476

**Comment by Salvationdk** [comment] 2016-05-17 12:25
that commit it stops working

**Comment by ermiyaeskandary** [comment] 2016-05-17 12:25
@Salvationdk Console log ?

**Comment by Salvationdk** [comment] 2016-05-17 12:25
wait ill reinstall

**Comment by Salvationdk** [comment] 2016-05-17 12:27
```
VM973:53Syntax error @ "Slither.io-bot"!
##########################
JSHINT output:
script: (W116) Expected ':' and instead saw 'bot' on line: 357 at character: 5
script: (E030) Expected an identifier and instead saw '=' on line: 357 at character: 9
script: (E033) Expected an operator and instead saw '(' on line: 357 at character: 11
script: (E020) Expected '}' to match '{' from line 64 and instead saw 'function' on line: 357 at character: 12
script: (W067) Bad invocation on line: 357 at character: 20
script: (W033) Missing semicolon on line: 357 at character: 22
script: (W033) Missing semicolon on line: 626 at character: 44
script: (W038) 'i' used out of scope on line: 671 at character: 25
script: (W038) 'i' used out of scope on line: 671 at character: 30
script: (W038) 'i' used out of scope on line: 671 at character: 45
script: (W038) 'i' used out of scope on line: 672 at character: 29
script: (W038) 'i' used out of scope on line: 673 at character: 57
script: (W038) 'i' used out of scope on line: 673 at character: 68
script: (W038) 'i' used out of scope on line: 675 at character: 57
script: (W038) 'i' used out of scope on line: 675 at character: 68
script: (W004) 'cell' is already defined on line: 678 at character: 30
script: (W033) Missing semicolon on line: 692 at character: 40
script: (W033) Missing semicolon on line: 715 at character: 75
script: (W041) Use '===' to compare with '0' on line: 731 at character: 50
script: (E030) Expected an identifier and instead saw ')' on line: 794 at character: 2
script: (E033) Expected an operator and instead saw '(' on line: 794 at character: 3
script: (W030) Expected an assignment or function call and instead saw an expression on line: 794 at character: 3
script: (W033) Missing semicolon on line: 794 at character: 4
script: (E030) Expected an identifier and instead saw ')' on line: 794 at character: 4
script: (W030) Expected an assignment or function call and instead saw an expression on line: 794 at character: 4
script: (W033) Missing semicolon on line: 960 at character: 36
script: (E020) Expected '}' to match '{' from line 960 and instead saw ':' on line: 960 at character: 36
script: (E020) Expected '}' to match '{' from line 805 and instead saw 'if' on line: 961 at character: 13
script: (W067) Bad invocation on line: 961 at character: 16
script: (W033) Missing semicolon on line: 961 at character: 32
script: (E020) Expected ')' to match '(' from line 798 and instead saw ':' on line: 983 at character: 21
script: (W033) Missing semicolon on line: 983 at character: 22
script: (W025) Missing name in function declaration on line: 983 at character: 31
script: (E030) Expected an identifier and instead saw ',' on line: 1007 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1007 at character: 10
script: (W033) Missing semicolon on line: 1007 at character: 11
script: (W028) Label 'onFrameUpdate' on function statement on line: 1009 at character: 24
script: (W025) Missing name in function declaration on line: 1009 at character: 32
script: (W004) '{a}' is already defined on line: 1009 at character: 32
script: (E030) Expected an identifier and instead saw ',' on line: 1040 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1040 at character: 10
script: (W033) Missing semicolon on line: 1040 at character: 11
script: (W028) Label 'oef' on function statement on line: 1042 at character: 14
script: (W025) Missing name in function declaration on line: 1042 at character: 22
script: (W004) '{a}' is already defined on line: 1042 at character: 22
script: (E030) Expected an identifier and instead saw ',' on line: 1049 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1049 at character: 10
script: (W033) Missing semicolon on line: 1049 at character: 11
script: (W028) Label 'quit' on function statement on line: 1052 at character: 15
script: (W025) Missing name in function declaration on line: 1052 at character: 23
script: (W004) '{a}' is already defined on line: 1052 at character: 23
script: (E030) Expected an identifier and instead saw ',' on line: 1061 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1061 at character: 10
script: (W033) Missing semicolon on line: 1061 at character: 11
script: (W028) Label 'onresize' on function statement on line: 1064 at character: 19
script: (W025) Missing name in function declaration on line: 1064 at character: 27
script: (W004) '{a}' is already defined on line: 1064 at character: 27
script: (E030) Expected an identifier and instead saw ',' on line: 1070 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1070 at character: 10
script: (W033) Missing semicolon on line: 1070 at character: 11
script: (W028) Label 'handleTextColor' on function statement on line: 1072 at character: 26
script: (W025) Missing name in function declaration on line: 1072 at character: 34
script: (W004) '{a}' is already defined on line: 1072 at character: 34
script: (E020) Expected ')' to match '(' from line 63 and instead saw ';' on line: 1077 at character: 6
script: (W033) Missing semicolon on line: 1077 at character: 7
script: (E041) Unrecoverable syntax error. (47% scanned) on line: 1077 at character: 1
##########################

SyntaxError: Unexpected identifier
    at u (eval at <anonymous> (unknown source), <anonymous>:52:286)
    at eval (eval at <anonymous> (unknown source), <anonymous>:1:24)
    at <anonymous>:2:95
    at b (<anonymous>:1:200)
    at ha (eval at <anonymous> (unknown source), <anonymous>:54:75)
    at F (eval at <anonymous> (unknown source), <anonymous>:52:339)
    at Object.Pa.create (eval at <anonymous> (unknown source), <anonymous>:61:195)
    at z (eval at <anonymous> (unknown source), <anonymous>:13:184)
```

**Comment by ermiyaeskandary** [comment] 2016-05-17 12:27
....

**Comment by ermiyaeskandary** [comment] 2016-05-17 12:28
Is it fixed now ?

**Comment by xpassionzxc** [comment] 2016-05-17 12:29
nope. did u update the version num?

**Comment by Salvationdk** [comment] 2016-05-17 12:29
nope

**Comment by Salvationdk** [comment] 2016-05-17 12:30
```
`Syntax error @ "Slither.io-bot"!
##########################
JSHINT output:
script: (W116) Expected ':' and instead saw 'bot' on line: 357 at character: 5
script: (E030) Expected an identifier and instead saw '=' on line: 357 at character: 9
script: (E033) Expected an operator and instead saw '(' on line: 357 at character: 11
script: (E020) Expected '}' to match '{' from line 64 and instead saw 'function' on line: 357 at character: 12
script: (W067) Bad invocation on line: 357 at character: 20
script: (W033) Missing semicolon on line: 357 at character: 22
script: (W033) Missing semicolon on line: 626 at character: 44
script: (W038) 'i' used out of scope on line: 671 at character: 25
script: (W038) 'i' used out of scope on line: 671 at character: 30
script: (W038) 'i' used out of scope on line: 671 at character: 45
script: (W038) 'i' used out of scope on line: 672 at character: 29
script: (W038) 'i' used out of scope on line: 673 at character: 57
script: (W038) 'i' used out of scope on line: 673 at character: 68
script: (W038) 'i' used out of scope on line: 675 at character: 57
script: (W038) 'i' used out of scope on line: 675 at character: 68
script: (W004) 'cell' is already defined on line: 678 at character: 30
script: (W033) Missing semicolon on line: 692 at character: 40
script: (W033) Missing semicolon on line: 715 at character: 75
script: (W041) Use '===' to compare with '0' on line: 731 at character: 50
script: (E030) Expected an identifier and instead saw ')' on line: 794 at character: 2
script: (E033) Expected an operator and instead saw '(' on line: 794 at character: 3
script: (W030) Expected an assignment or function call and instead saw an expression on line: 794 at character: 3
script: (W033) Missing semicolon on line: 794 at character: 4
script: (E030) Expected an identifier and instead saw ')' on line: 794 at character: 4
script: (W030) Expected an assignment or function call and instead saw an expression on line: 794 at character: 4
script: (W033) Missing semicolon on line: 960 at character: 36
script: (E020) Expected '}' to match '{' from line 960 and instead saw ':' on line: 960 at character: 36
script: (E020) Expected '}' to match '{' from line 805 and instead saw 'if' on line: 961 at character: 13
script: (W067) Bad invocation on line: 961 at character: 16
script: (W033) Missing semicolon on line: 961 at character: 32
script: (E020) Expected ')' to match '(' from line 798 and instead saw ':' on line: 983 at character: 21
script: (W033) Missing semicolon on line: 983 at character: 22
script: (W025) Missing name in function declaration on line: 983 at character: 31
script: (E030) Expected an identifier and instead saw ',' on line: 1007 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1007 at character: 10
script: (W033) Missing semicolon on line: 1007 at character: 11
script: (W028) Label 'onFrameUpdate' on function statement on line: 1009 at character: 24
script: (W025) Missing name in function declaration on line: 1009 at character: 32
script: (W004) '{a}' is already defined on line: 1009 at character: 32
script: (E030) Expected an identifier and instead saw ',' on line: 1040 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1040 at character: 10
script: (W033) Missing semicolon on line: 1040 at character: 11
script: (W028) Label 'oef' on function statement on line: 1042 at character: 14
script: (W025) Missing name in function declaration on line: 1042 at character: 22
script: (W004) '{a}' is already defined on line: 1042 at character: 22
script: (E030) Expected an identifier and instead saw ',' on line: 1049 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1049 at character: 10
script: (W033) Missing semicolon on line: 1049 at character: 11
script: (W028) Label 'quit' on function statement on line: 1052 at character: 15
script: (W025) Missing name in function declaration on line: 1052 at character: 23
script: (W004) '{a}' is already defined on line: 1052 at character: 23
script: (E030) Expected an identifier and instead saw ',' on line: 1061 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1061 at character: 10
script: (W033) Missing semicolon on line: 1061 at character: 11
script: (W028) Label 'onresize' on function statement on line: 1064 at character: 19
script: (W025) Missing name in function declaration on line: 1064 at character: 27
script: (W004) '{a}' is already defined on line: 1064 at character: 27
script: (E030) Expected an identifier and instead saw ',' on line: 1070 at character: 10
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1070 at character: 10
script: (W033) Missing semicolon on line: 1070 at character: 11
script: (W028) Label 'handleTextColor' on function statement on line: 1072 at character: 26
script: (W025) Missing name in function declaration on line: 1072 at character: 34
script: (W004) '{a}' is already defined on line: 1072 at character: 34
script: (E020) Expected ')' to match '(' from line 63 and instead saw ';' on line: 1077 at character: 6
script: (W033) Missing semicolon on line: 1077 at character: 7
script: (E041) Unrecoverable syntax error. (47% scanned) on line: 1077 at character: 1
##########################

SyntaxError: Unexpected identifier
    at u (eval at <anonymous> (unknown source), <anonymous>:52:286)
    at eval (eval at <anonymous> (unknown source), <anonymous>:1:24)
    at <anonymous>:2:95
    at b (<anonymous>:1:200)
    at ha (eval at <anonymous> (unknown source), <anonymous>:54:75)
    at F (eval at <anonymous> (unknown source), <anonymous>:52:339)
    at Object.Pa.create (eval at <anonymous> (unknown source), <anonymous>:61:195)
    at z (eval at <anonymous> (unknown source), <anonymous>:13:184)`
```

**Comment by ermiyaeskandary** [comment] 2016-05-17 12:35
Should be fixed...

**Comment by Salvationdk** [comment] 2016-05-17 12:36
```
VM11775:53Syntax error @ "Slither.io-bot"!
##########################
JSHINT output:
script: (W116) Expected ':' and instead saw 'bot' on line: 357 at character: 5
script: (E030) Expected an identifier and instead saw '=' on line: 357 at character: 9
script: (E033) Expected an operator and instead saw '(' on line: 357 at character: 11
script: (E020) Expected '}' to match '{' from line 64 and instead saw 'function' on line: 357 at character: 12
script: (W067) Bad invocation on line: 357 at character: 20
script: (W033) Missing semicolon on line: 357 at character: 22
script: (W033) Missing semicolon on line: 626 at character: 44
script: (W038) 'i' used out of scope on line: 671 at character: 25
script: (W038) 'i' used out of scope on line: 671 at character: 30
script: (W038) 'i' used out of scope on line: 671 at character: 45
script: (W038) 'i' used out of scope on line: 672 at character: 29
script: (W038) 'i' used out of scope on line: 673 at character: 57
script: (W038) 'i' used out of scope on line: 673 at character: 68
script: (W038) 'i' used out of scope on line: 675 at character: 57
script: (W038) 'i' used out of scope on line: 675 at character: 68
script: (W004) 'cell' is already defined on line: 678 at character: 30
script: (W033) Missing semicolon on line: 692 at character: 40
script: (W033) Missing semicolon on line: 715 at character: 75
script: (W041) Use '===' to compare with '0' on line: 731 at character: 50
script: (E030) Expected an identifier and instead saw ')' on line: 794 at character: 2
script: (E033) Expected an operator and instead saw '(' on line: 794 at character: 3
script: (W030) Expected an assignment or function call and instead saw an expression on line: 794 at character: 3
script: (W033) Missing semicolon on line: 794 at character: 4
script: (E030) Expected an identifier and instead saw ')' on line: 794 at character: 4
script: (W030) Expected an assignment or function call and instead saw an expression on line: 794 at character: 4
script: (W054) The Function constructor is a form of eval on line: 1187 at character: 33
script: (W041) Use '===' to compare with '0' on line: 1628 at character: 29
script: (W004) 'col' is already defined on line: 1729 at character: 21
script: (W004) 'row' is already defined on line: 1730 at character: 21
script: (W004) 'col' is already defined on line: 1754 at character: 21
script: (W004) 'row' is already defined on line: 1755 at character: 21
script: (W032) Unnecessary semicolon on line: 1855 at character: 85
script: (W014) Bad line breaking before '||' on line: 1963 at character: 25
script: (W014) Bad line breaking before '||' on line: 1967 at character: 25
script: (W033) Missing semicolon on line: 1968 at character: 93
script: (W033) Missing semicolon on line: 1972 at character: 41
script: (W033) Missing semicolon on line: 2023 at character: 62
script: (W041) Use '===' to compare with '0' on line: 2074 at character: 29
script: (W033) Missing semicolon on line: 2126 at character: 66
script: (W033) Missing semicolon on line: 2130 at character: 66
script: (W033) Missing semicolon on line: 2134 at character: 66
script: (W033) Missing semicolon on line: 2137 at character: 66
script: (W030) Expected an assignment or function call and instead saw an expression on line: 2164 at character: 38
script: (W030) Expected an assignment or function call and instead saw an expression on line: 2165 at character: 38
script: (W033) Missing semicolon on line: 2270 at character: 6
script: (E019) Unmatched '{' on line: 61 at character: 26
script: (E041) Unrecoverable syntax error. (100% scanned) on line: 2272 at character: 
##########################

```

**Comment by ermiyaeskandary** [comment] 2016-05-17 12:36
@Salvationdk Are you sure that is the latest version ?

**Comment by Salvationdk** [comment] 2016-05-17 12:36
Not yet

**Comment by xpassionzxc** [comment] 2016-05-17 12:37
`666VM23003:1307 Uncaught TypeError: collisionGrid.markDirty is not a function`
- from latest version

**Comment by Salvationdk** [comment] 2016-05-17 12:38
https://github.com/ErmiyaEskandary/Slither.io-bot/commit/167299

`462VM13965:1307 Uncaught TypeError: collisionGrid.markDirty is not a function`

**Comment by ermiyaeskandary** [comment] 2016-05-17 12:40
Should be fixed

**Comment by Salvationdk** [comment] 2016-05-17 12:41
confirmed working as of now

**Comment by xpassionzxc** [comment] 2016-05-17 12:41
```
1791
VM528:1307 Uncaught TypeError: collisionGrid.markDirty is not a function
astar.search    @   VM528:1307
collisionGrid.generatePath  @   VM528:1905
bot.state.trackFood @   VM528:674
bot.astarFoodFinder @   VM528:790
bot.thinkAboutGoals @   VM528:572
window.loop @   VM528:1092
userInterface.oef   @   VM528:1054
(anonymous function)    @   VM1042:1
```

**Closed as completed** 2016-05-17 12:41 UTC
Labels: type:bug, status:confirmed

**Comment by ermiyaeskandary** [comment] 2016-05-17 14:54
So is it a new error ?

**Comment by ermiyaeskandary** [comment] 2016-05-17 14:54
@xpassionzxc Make sure it is the latest version

**Comment by Drflash55** [comment] 2016-05-17 14:55
I added the confirmed label, because it was... confirmed as a bug...

**Comment by ermiyaeskandary** [comment] 2016-05-17 14:55
Latest version ?

**Comment by Drflash55** [comment] 2016-05-17 14:57
@ErmiyaEskandary Can't test... not at home... But, if you don't find anything... you can remove the label.

**Comment by ermiyaeskandary** [comment] 2016-05-17 15:00
@xpassionzxc Please make a new issue **if you are 100% sure you are using the latest version and it is still there.**

**Comment by ChadSki** [comment] 2016-05-17 18:21
Related to [#191](https://github.com/ErmiyaEskandary/Slither.io-bot/issues/191)  :P
